<!-- In admin/index.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Rise Above Partners - Admin</title>
</head>
<body>
  <!-- Include the script that builds the page and powers Decap CMS -->
  <script src="https://unpkg.com/decap-cms@^3.0.0/dist/decap-cms.js"></script>
  
  <!-- Manual initialization -->
  <script>
    window.CMS_MANUAL_INIT = true;
    
    // Initialize CMS manually with explicit config path
    window.addEventListener('load', function() {
      CMS.init({
        config: {
          backend: {
            name: 'github',
            repo: 'BeBraveBeKind/rise-above-website',
            branch: 'main',
            base_url: 'https://rise-above.net',
            auth_endpoint: 'api/auth-callback'
          },
          media_folder: "images/content",
          public_folder: "/images/content",
          collections: [
            {
              name: "services",
              label: "Services",
              folder: "_data/services",
              create: true,
              extension: "json",
              format: "json",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { label: "Description", name: "description", widget: "text" },
                { label: "Image", name: "image", widget: "image" },
                { label: "Order", name: "order", widget: "number" }
              ]
            }
          ]
        }
      });
    });
  </script>
</body>
</html>