[[headers]]
  for = "*.yml"
  [headers.values]
    Content-Type = "text/yaml"
    
[build]
  publish = "/"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# API redirects for Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"