[
build
]
  publish = "/"
  functions = "netlify/functions"

[[
plugins
]]
  package = "@netlify/plugin-lighthouse"

# Admin panel SPA routing
[[
redirects
]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# API redirects for Netlify Functions
[[
redirects
]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security and caching
[[
headers
]]
  for = "/*"
  [
headers.values
]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://*.github.com https://unpkg.com; connect-src 'self' https://api.github.com https://unpkg.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com; img-src 'self' data: https://*.githubusercontent.com; font-src 'self' https://fonts.gstatic.com;"
    
# Set caching for static assets
[[
headers
]]
  for = "/images/*"
  [
headers.values
]
    Cache-Control = "public, max-age=31536000"

[[
headers
]]
  for = "/css/*"
  [
headers.values
]
    Cache-Control = "public, max-age=31536000"

[[
headers
]]
  for = "/js/*"
  [
headers.values
]
    Cache-Control = "public, max-age=31536000"