backend:
  name: github
  repo: BeBraveBeKind/rise-above-website
  branch: main
  base_url: https://rise-above.net
  auth_endpoint: api/auth-callback
  
media_folder: "images/content"
public_folder: "/images/content"

local_backend: true

# Site settings
site_url: https://rise-above.net
display_url: https://rise-above.net
logo_url: /images/brand/logomark.svg

# Editorial workflow
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "_data/home.json"
        fields:
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Description", name: "heroDescription", widget: "text"}
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "select", options: ["strategic", "creative", "data"]}
  
  - name: "services"
    label: "Services"
    folder: "_data/services"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Order", name: "order", widget: "number"}
  
  - name: "testimonials"
    label: "Testimonials"
    folder: "_data/testimonials"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Client Name", name: "name", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Testimonial", name: "testimonial", widget: "text"}
      - {label: "Avatar", name: "avatar", widget: "image", required: false}
  
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "select", options: ["Strategy", "Content", "Digital", "Analytics"]}
      - {label: "Body", name: "body", widget: "markdown"}